FROM node:18-alpine

WORKDIR /app

# Install dependencies based on package.json
COPY package*.json ./
RUN npm install

# Copy source
COPY . .

# Expose port
EXPOSE 3000

# Start dev server
CMD ["npm", "run", "dev"]
